name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up environment variables
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"

      - name: Configure Git Config
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"

      - name: Initiate Installation and build
        run: |
          npm install
          node server.js

      - name: Commit changes and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          git add .
          git diff
          git commit -m "Update README.md"
          git push origin main
